### ISSUE TITLE
Hey great tool, but if the domain is also shown in the output it would be very easy to find where is the token

### ISSUE THREAD

**Issue by yourbuddy25** [xyele/zile#2]
I have edited the code to add domains after key, you can edit it more better, and I have not changed the code for stdin read `extract(str(sys.stdin.read()),'test')` , as I had less time. I hope you agree with my suggestion.

CODE : (Changed code where #EDIT comment is there)
[zile.txt](https://github.com/xyele/zile/files/4381352/zile.txt)

**Comment by xyele** [comment]
Hey! For next time, can you fork it and send a pull request? Also probably your code gonna give an error when the user used --colored parameter because you were not put z parameter into the output string. Also, I'm gonna add source of key with the next release/commit.

Thanks for suggestion.
