### ISSUE TITLE
googleMapsApiKey issue

### ISSUE THREAD

**Issue by alfonsocaponi** [xyele/zile#3]
I've some evidence about googleMapsApiKey:

# sed 's/"/\n/g' * | grep "AIza"
AIzaSyA14a3T63lNoyN80F6MBCXekXnOJy*****
AIzaSyA14a3T63lNoyN80F6MBCXekXnOJy*****
..

# python3 zile.py --file
#

but zile.py didn't find anything. Maybe I'm doing anything wrong.

Thank you

**Comment by xyele** [comment]
could you share full of text with me?
